#!/bin/bash

sv start prestart && sleep 1 || exit 1
sv start st2auth && sleep 1 || exit 1
sv start st2api && sleep 1 || exit 1
sv start st2stream && sleep 1 || exit 1

source /etc/envvars

export ST2_HOSTNAME="127.0.0.1"
export ST2_API="${ST2_API:-http://${ST2_HOSTNAME}/api}"
export ST2_AUTH_URL="${ST2_AUTH_URL:-http://${ST2_HOSTNAME}/auth}"
export ST2_STREAM_URL="${ST2_STREAM_URL:-http://${ST2_HOSTNAME}/stream}"
export ST2_WEBUI_URL="${ST2_WEBUI_URL}"

until curl $ST2_API; do echo "waiting for $ST2_API to come online..."; sleep 3; done;
until curl $ST2_AUTH_URL; do echo "waiting for $ST2_AUTH_URL to come online..."; sleep 3; done;

export ST2_AUTH_TOKEN=`st2 auth -t -p $ST2_AUTH_PASSWORD $ST2_AUTH_USERNAME`
export ST2_API_KEY=`st2 apikey create -k -m '{"used_by": "st2chatops"}'`

st2ctl reload --register-all

cd /opt/stackstorm/chatops

exec 2>&1
exec ./bin/hubot
