#!/bin/bash

sv start prestart && sleep 1 || exit 1

source /etc/envvars

mkdir -p /var/run/mistral

exec 2>&1
exec /opt/stackstorm/mistral/bin/gunicorn --log-file /var/log/mistral/mistral-api.log -b 127.0.0.1:8989 -w 2 mistral.api.wsgi --graceful-timeout 10 --pid /var/run/mistral/mistral.pid
